# Introduction

Sablefish (*Anoplopoma fimbria*) are a commercially valuable species that are harvested in British Columbia (BC) using trap, longline and trawl gear as part of the integrated groundfish fishery. For ten years (`r yr-8` to `r yr+1`),  BC fishermen landed an average of `r format(avg.Ten.yrs[1,1], big.mark=",")` metric tons of sablefish annually.  The majority of sablefish in `r yr`  were captured by longline trap gear (`r trap.Percent[1,1]`\%) and longline hook gear  (`r longlne.Percent[1,1]`\%); in  `r yr+1`, the majority of sablefish were  captured  by longline trap gear  (`r trap.Percent2[1,1]`\%) and longline hook gear  (`r longlne.Percent2[1,1]`\%). Commercial harvest of sablefish typically occurs at depths up to 985 fathoms, along the steep-walled slopes off the west coast of Haida Gwaii, in the complex  troughs  of Queen  Charlotte Sound, and in the steep canyons and ridges off the west coast of Vancouver Island. 

Fishery-independent research and assessment surveys for sablefish have been conducted in BC coastal waters since 1988. The methodology for the `r yr` and `r yr+1` surveys included a stratified random sampling (StRS) component and a traditional component.    The random component random was composed of StRS sets at five depth-stratified areas. The traditional component was comprised of standardized sets at nine offshore indexing localities and four mainland inlets.  In addition, an exploratory component was added to the `r yr` survey.

These surveys are used to obtain catch rate data, gather biological samples, capture oceanographic measurements and collect tag release and recapture data. For details about past survey designs, see the historic overview provided by @Wyeth2003 and @Wyeth2004b. For details on specific surveys conducted from 1988 through 1993 see @Smith1996; for surveys in 1994 and 199five see @Downes1997; for surveys from 1996 to 2000 see @Wyeth2003.  For the 2001 through 2006 surveys see @Wyeth2003, @Wyeth2004a, @Wyeth2004b and @Wyeth2006, respectively.  

This technical report details survey operations and summarize biological data collected on the `r yr` and `r yr+1` chartered surveys aboard the F/V `r boat1`. Tables and figures referred to in the main text are numbered sequentially. Tables and figures in the appendices are labelled with a letter code.